fix error (doc:fetch-data-via-sdk.mdx)
aptos-labs/developer-docs pull request #497
Opened 2024-07-08 15:21 UTC by caoyang2002

### Description

The second code block example, which is labeled as `fetch-data.ts`; correct the erroneous syntax to a nested object.

### Checklist

The `apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx`

> appendix:

```ts
queryIndexer<T extends {}>(args: {
    query: GraphqlQuery;
}): Promise<T>;
```

```
type GraphqlQuery = {
    query: string;
    variables?: {};
};
```

- Do all Lints pass?
  - [ ] Have you ran `pnpm spellcheck`?
  - [ ] Have you ran `pnpm fmt`?
  - [ ] Have you ran `pnpm lint`?

2024-07-08 15:32 UTC, WGB5445 commented
Very good. Thank you very much.

2024-07-08 15:37 UTC, banool requested changes

2024-07-08 15:37 UTC, banool commented on apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx
> +  const ntf_collection_info = aptos.queryIndexer({
This should still be called `ledgerInfo` yeah?

2024-07-08 15:39 UTC, 0xmaayan commented on apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx
> +  const ntf_collection_info = aptos.queryIndexer({
```suggestion
  const ledgerInfo = aptos.queryIndexer({
```

2024-07-08 15:39 UTC, 0xmaayan commented on apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx
> +      variables: {}, // If the query does not require variables, it can be an empty object here.
If the query does not require variables, we can simply not add a `variables` field

https://github.com/aptos-labs/aptos-ts-sdk/blob/main/tests/e2e/api/general.test.ts#L224

2024-07-08 15:40 UTC, 0xmaayan commented
> ### Description
> The second code block example, which is labeled as `fetch-data.ts`; correct the erroneous syntax to a nested object.
> 
> ### Checklist
> The `apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx`
> 
> > appendix:
> 
> ```ts
> queryIndexer<T extends {}>(args: {
>     query: GraphqlQuery;
> }): Promise<T>;
> ```
> 
> ```
> type GraphqlQuery = {
>     query: string;
>     variables?: {};
> };
> ```
> 
> * Do all Lints pass?
>   
>   * [ ]  Have you ran `pnpm spellcheck`?
>   * [ ]  Have you ran `pnpm fmt`?
>   * [ ]  Have you ran `pnpm lint`?

Thanks for the PR! The issue is with the object syntax with a missing `query` field. The `variables` field is not required if the query does not require variables

2024-07-08 16:37 UTC, 0xmaayan approved these changes

2024-08-16 03:38 UTC, gregnazario approved these changes

2024-08-21 20:39 UTC, closed without merging

2024-08-21 20:39 UTC, gregnazario commented
Looks like all of these changes have gotten in already.  Thanks for the contribution!