documentation improvements (typos, links, images)
aptos-labs/developer-docs pull request #731
Opened 2024-12-08 12:46 UTC by savvar9991

The image is restored
Fixed a typo
Improved Ivezual display
replaced non -working link to the correct

2024-12-08 15:50 UTC, ziaptos approved these changes

2024-12-10 17:17 UTC, gregnazario requested changes
Generally good, but there are a few updates where changes to `img` tags don't make sense

2024-12-10 17:17 UTC, gregnazario commented on apps/nextra/pages/en/build/sdks/ts-sdk.mdx
>    </a>
Hmm, these seem to work right now, any reason to change from markdown to HTML?

2024-12-11 02:41 UTC, savvar9991 reviewed
I've addressed the feedback:

1. For node-networks-sync.mdx: Fixed the image path to correctly display the network diagram (provided before/after screenshots showing the fix)
2. For ts-sdk.mdx: Will keep the original dynamic image implementation and create a separate issue for server setup requirements

2024-12-11 02:41 UTC, savvar9991 commented on apps/nextra/pages/en/network/blockchain/node-networks-sync.mdx
> +![v-fn-network.svg](/apps/nextra/public/docs/v-fn-network.svg)
Actually, the image with the original path isn't working - it shows as a broken image. The new path I added points to the correct location of the file in the project structure (/apps/nextra/public/docs/v-fn-network.svg), which makes the image display properly.

Would you like me to show you the difference between how it looks with both paths?
Screenshot before changes:
![image](https://github.com/user-attachments/assets/d018aec5-245e-49d2-a74f-c5991b0bd361)
Screenshot after changes:
![image](https://github.com/user-attachments/assets/4e9e505b-7b4c-470a-bc43-cbbec83d33c2)

2024-12-11 18:53 UTC, gregnazario commented
Okay, I get it now, you're looking at GitHub, rather than the website `aptos.dev` directly.  Mainly focused on readability there, so will need to double check on the preview site

2025-02-11 01:59 UTC, closed without merging